name: Mooltiselect
author: marcelo.origoni
category: Forms
tags: [forms, multiselect, sortable, combo, select]
docs: http://marcelo.origoni.com.ar/mooltiSelect/
demo: http://marcelo.origoni.com.ar/mooltiSelect/demo.php
current: 1.5
