name: Mooltiselect
authors: 
- Marcelo Origoni
category: Forms
tags: [forms, multiselect, sortable]
#docs: http://marcelo.origoni.com.ar/mooltiselect/
#demo: http://marcelo.origoni.com.ar/mooltiselect/demo.php
#current: 1.1.2